---
- name: check shipyard-controller
  command: docker inspect -f \{\{.State.Running\}\} shipyard-controller
  register: status
  changed_when: status.rc != 0
  ignore_errors: yes
 
- name: install shipyard-controller
  command: docker run -ti -d --restart=always --name shipyard-controller --link shipyard-rethinkdb:rethinkdb --link shipyard-swarm-manager:swarm -p {{shipyard_port}}:{{shipyard_port}} --volumes-from=shipyard-certs shipyard/shipyard:latest --debug server --listen :{{shipyard_port}} -d tcp://swarm:{{swarm_port}}
  when: status.rc != 0
